# Generated by Django 2.0 on 2017-12-07 04:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MEM', 'Member'), ('AFF', 'Affiliate'), ('RET', 'Retired'), ('KIA', 'Killed in action')], default='AFF', max_length=3)),
                ('callsign', models.CharField(max_length=255)),
                ('rsi_url', models.URLField(default='https://robertsspaceindustries.com/citizens/croberts68')),
                ('birth_date', models.DateField(default=datetime.datetime(1980, 1, 1, 0, 0))),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('primary_activity', models.CharField(choices=[('HUN', 'Bounty Hunting'), ('ENG', 'Engineering'), ('EXP', 'Exploration'), ('FRE', 'Freelancing'), ('INF', 'Infiltration'), ('PIR', 'Piracy'), ('RES', 'Resources'), ('SCO', 'Scouting'), ('SEC', 'Security'), ('SMU', 'Smuggling'), ('SOC', 'Social'), ('TRD', 'Trading'), ('TRN', 'Transport')], default='RES', max_length=3)),
                ('secondary_activity', models.CharField(choices=[('HUN', 'Bounty Hunting'), ('ENG', 'Engineering'), ('EXP', 'Exploration'), ('FRE', 'Freelancing'), ('INF', 'Infiltration'), ('PIR', 'Piracy'), ('RES', 'Resources'), ('SCO', 'Scouting'), ('SEC', 'Security'), ('SMU', 'Smuggling'), ('SOC', 'Social'), ('TRD', 'Trading'), ('TRN', 'Transport')], default='TRD', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
