# Generated by Django 2.0 on 2017-12-16 06:09

from django.db import migrations
import employees.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, storage=employees.models.LocalFileSystemStorage(), upload_to=employees.models.upload_path_handler),
        ),
    ]
