# Generated by Django 2.0 on 2017-12-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('MEM', 'Member'), ('AFF', 'Affiliate'), ('RET', 'Retired'), ('KIA', 'Killed in action'), ('PRE', 'President'), ('SEC', 'Secretary'), ('CFO', 'Chief Financial Officer')], default='AFF', max_length=3),
        ),
    ]
