# Generated by Django 2.0 on 2017-12-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20171216_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emp_no']},
        ),
    ]
