# Generated by Django 2.0 on 2018-01-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20171228_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-emp_no']},
        ),
    ]
